# Generated by Django 2.2.26 on 2022-07-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='comments.Comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='comments.Comment')),
            ],
        ),
    ]
